@extends('admin.layouts.master')

@section('page_title')
    Laporan Klaster  | UMKM Be Digital Sidamanik
@endsection

@section('breadcrumb')
    <div class="page-header">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Laporan</a></li>
                <li class="breadcrumb-item active" aria-current="page">Laporan Klaster </li>
            </ol>
        </nav>
    </div>
@endsection

@section('content')
<div class="card shadow">
    <div class="card-header border-0">
        <div class="row align-items-center">
            <div class="col">
                <h2 class="mb-0">Laporan Klaster</h2>
            </div>
        </div>
    </div>
    <div class="card-body border-0">
        <!-- Projects table -->
        <table class="table align-items-center table-flush" id="myTable">
            <thead class="thead-light">
                <tr class="text-center">
                    <th scope="col">No</th>
                    <th scope="col">Penanggung Jawab</th>
                    <th scope="col">Nama Cluster</th>
                    <th scope="col">Alamat</th>
                </tr>
            </thead>
            <tbody>
                @foreach($cluster as $k => $d)
                <tr class="text-center">
                    <td scope="row">{{ $k + 1 }}</td>
                    <td scope="row">{{$d->penanggung_jawab}}</td>
                    <td scope="row">{{$d->nama}}</td>
                    <td scope="row">{{$d->alamat}}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
{{-- <div class="dashboard-ecommerce">
    <div class="container-fluid dashboard-content ">
        <div class="row">
            <!-- ============================================================== -->
            <!-- basic table  -->
            <!-- ============================================================== -->
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-6">
                                <h5>Laporan Cluster</h5>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered first" id="dt_tables">
                                <thead>
                                    <tr>
                                        <th>Penanggung Jawab</th>
                                        <th>Nama Cluster</th>
                                        <th>Alamat</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($cluster as $d)
                                    <tr>
                                        <td>{{$d->penanggung_jawab}}</td>
                                        <td>{{$d->nama}}</td>
                                        <td>{{$d->alamat}}</td>
                                    </tr>
                                    @endforeach
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- end basic table  -->
            <!-- ============================================================== -->
        </div>
    </div>
</div> --}}

@endsection

@push('scripts')
    <script>
        // $(document).ready( function () {
        //     $('#my').dataTable( {
        //         "sDom": 'T<"clear">lfrtip',
        //         "oTableTools": {
        //             "aButtons": [
        //                 {
        //                     "sExtends": "print",
        //                     "sMessage": "Generated by DataTables"
        //                 }
        //             ]
        //         }
        //     } );
        // } );
        $(document).ready(function () {
            $('#myTable').DataTable(
                {
                    dom: 'Bfrtip',
                    buttons: [
                        'print'
                    ]
                }
            );
        });
    </script>
@endpush
